# Generated by Django 5.0.3 on 2024-03-27 16:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(default=accounts.models.generate_unique_name, max_length=25),
        ),
    ]
