# Generated by Django 5.0.3 on 2024-03-27 21:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=15, validators=[accounts.models.validate_password]),
        ),
    ]
