# Generated by Django 5.0.3 on 2024-03-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_personajes_alter_userprofile_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='personajes',
        ),
    ]
