# Generated by Django 5.0.3 on 2024-03-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potion_craft', '0003_remove_esencia_cantidad_remove_ingrediente_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='descripcion',
            field=models.CharField(max_length=140),
        ),
    ]
