# Generated by Django 5.0.3 on 2024-03-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potion_craft', '0005_potion_alteracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potion',
            name='alteracion',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
