# Generated by Django 5.0.3 on 2024-04-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potion_craft', '0010_esencia_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esencia',
            name='valor',
            field=models.CharField(default='1', max_length=25),
        ),
    ]
