# Generated by Django 5.0.3 on 2024-04-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potion_craft', '0011_alter_esencia_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='genero',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='raza',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
